"""Generated by tests/extract_civ7_data.py from the Civ 7 install XML.
Do not edit by hand; re-run the extractor.
"""

ANTIQUITY_DISCOVERY_TYPES: tuple[str, ...] = (
    'GOODYHUT_CULTURE',
    'GOODYHUT_GOLD',
    'GOODYHUT_HAPPINESS',
    'GOODYHUT_MILITARY',
    'GOODYHUT_SCIENCE',
    'GOODYHUT_SURVIVORS',
)

EXPLORATION_DISCOVERY_TYPES: tuple[str, ...] = (
    'GOODYHUT_CULTURE',
    'GOODYHUT_GOLD',
    'GOODYHUT_HAPPINESS',
    'GOODYHUT_MILITARY',
    'GOODYHUT_SCIENCE',
    'GOODYHUT_SURVIVORS',
)

MODERN_DISCOVERY_TYPES: tuple[str, ...] = (
    'GOODYHUT_CULTURE',
    'GOODYHUT_GOLD',
    'GOODYHUT_HAPPINESS',
    'GOODYHUT_MILITARY',
    'GOODYHUT_SCIENCE',
    'GOODYHUT_SURVIVORS',
)

