"""Generated by tests/extract_civ7_data.py from the Civ 7 install XML.
Do not edit by hand; re-run the extractor.
"""

PANTHEON_BELIEFS: tuple[str, ...] = (
    'PANTHEON_BONUS_1',
    'PANTHEON_BONUS_10',
    'PANTHEON_BONUS_11',
    'PANTHEON_BONUS_12',
    'PANTHEON_BONUS_13',
    'PANTHEON_BONUS_14',
    'PANTHEON_BONUS_15',
    'PANTHEON_BONUS_16',
    'PANTHEON_BONUS_17',
    'PANTHEON_BONUS_18',
    'PANTHEON_BONUS_2',
    'PANTHEON_BONUS_3',
    'PANTHEON_BONUS_4',
    'PANTHEON_BONUS_5',
    'PANTHEON_BONUS_6',
    'PANTHEON_BONUS_7',
    'PANTHEON_BONUS_8',
    'PANTHEON_BONUS_9',
)
