"""Generated by tests/extract_civ7_data.py from the Civ 7 install XML.
Do not edit by hand; re-run the extractor.
"""

# Per-Age table: base_unit_type -> {civ_trait: civ_unique_unit}
# Used by the apworld + mod to deliver "Tier N <class> Unit"
# AP items resolved at grant time to the player's civ-matching
# unit variant (default = base unit if no trait matches).

BASE_UNIT_TO_VARIANTS: dict[str, dict[str, dict[str, str]]] = {
    'Antiquity': {
        'UNIT_ARCHER': {
            'TRAIT_HAN': 'UNIT_NU_2',
            'TRAIT_MAYA': 'UNIT_HULCHE_2',
            'TRAIT_MISSISSIPPIAN': 'UNIT_BURNING_ARROW_2',
        },
        'UNIT_ARMY_COMMANDER': {
            'TRAIT_PERSIA': 'UNIT_HAZARAPATIS',
            'TRAIT_ROME': 'UNIT_LEGATUS',
        },
        'UNIT_CHARIOT': {
            'TRAIT_KHMER': 'UNIT_DANTINAS_TATHA',
            'TRAIT_MAURYA': 'UNIT_PURABHETTARAH',
        },
        'UNIT_GALLEY': {
            'TRAIT_AKSUM': 'UNIT_DHOW',
        },
        'UNIT_HORSEMAN': {
            'TRAIT_KHMER': 'UNIT_DANTINAS_TATHA_2',
            'TRAIT_MAURYA': 'UNIT_PURABHETTARAH_2',
        },
        'UNIT_MERCHANT': {
            'TRAIT_KHMER': 'UNIT_VAISHYA',
            'TRAIT_MISSISSIPPIAN': 'UNIT_WATONATHI',
        },
        'UNIT_PHALANX': {
            'TRAIT_EGYPT': 'UNIT_MEDJAY_3',
            'TRAIT_GREECE': 'UNIT_HOPLITE_3',
            'TRAIT_PERSIA': 'UNIT_IMMORTAL_2',
            'TRAIT_ROME': 'UNIT_LEGION_2',
        },
        'UNIT_QUADRIREME': {
            'TRAIT_AKSUM': 'UNIT_DHOW_2',
        },
        'UNIT_SCOUT': {
            'TRAIT_MAYA': 'UNIT_JAGUAR_SLAYER',
        },
        'UNIT_SETTLER': {
            'TRAIT_MAURYA': 'UNIT_NAGARIKA',
        },
        'UNIT_SLINGER': {
            'TRAIT_HAN': 'UNIT_NU',
            'TRAIT_MAYA': 'UNIT_HULCHE',
            'TRAIT_MISSISSIPPIAN': 'UNIT_BURNING_ARROW',
        },
        'UNIT_SPEARMAN': {
            'TRAIT_EGYPT': 'UNIT_MEDJAY_2',
            'TRAIT_GREECE': 'UNIT_HOPLITE_2',
            'TRAIT_PERSIA': 'UNIT_IMMORTAL',
            'TRAIT_ROME': 'UNIT_LEGION',
        },
        'UNIT_TRADE_SHIP': {
            'TRAIT_AKSUM': 'UNIT_TANKWA',
        },
        'UNIT_WARRIOR': {
            'TRAIT_EGYPT': 'UNIT_MEDJAY',
            'TRAIT_GREECE': 'UNIT_HOPLITE',
        },
    },
    'Exploration': {
        'UNIT_ARMY_COMMANDER': {
            'TRAIT_MONGOLIA': 'UNIT_NOYAN',
        },
        'UNIT_ARQUEBUSIER': {
            'TRAIT_INCA': 'UNIT_WARAKAQ_3',
            'TRAIT_MONGOLIA': 'UNIT_KESHIG_3',
        },
        'UNIT_CARRACK': {
            'TRAIT_CHOLA': 'UNIT_KALAM_2',
            'TRAIT_MAJAPAHIT': 'UNIT_CETBANG_2',
        },
        'UNIT_COG': {
            'TRAIT_CHOLA': 'UNIT_KALAM',
            'TRAIT_MAJAPAHIT': 'UNIT_CETBANG',
        },
        'UNIT_COURSER': {
            'TRAIT_ABBASID': 'UNIT_MAMLUK',
            'TRAIT_NORMAN': 'UNIT_CHEVALER',
        },
        'UNIT_CROSSBOWMAN': {
            'TRAIT_INCA': 'UNIT_WARAKAQ_2',
            'TRAIT_MONGOLIA': 'UNIT_KESHIG_2',
        },
        'UNIT_FLEET_COMMANDER': {
            'TRAIT_CHOLA': 'UNIT_OTTRU',
        },
        'UNIT_GALLEON': {
            'TRAIT_CHOLA': 'UNIT_KALAM_3',
            'TRAIT_MAJAPAHIT': 'UNIT_CETBANG_3',
        },
        'UNIT_HEAVY_ARCHER': {
            'TRAIT_INCA': 'UNIT_WARAKAQ',
            'TRAIT_MONGOLIA': 'UNIT_KESHIG',
        },
        'UNIT_KNIGHT': {
            'TRAIT_ABBASID': 'UNIT_MAMLUK_2',
            'TRAIT_NORMAN': 'UNIT_CHEVALER_2',
        },
        'UNIT_LANCER': {
            'TRAIT_ABBASID': 'UNIT_MAMLUK_3',
            'TRAIT_NORMAN': 'UNIT_CHEVALER_3',
        },
        'UNIT_MAN_AT_ARMS': {
            'TRAIT_HAWAII': 'UNIT_LEIOMANO_2',
            'TRAIT_MING': 'UNIT_XUNLEICHONG_2',
            'TRAIT_SONGHAI': 'UNIT_GOLD_BANGLES_2',
            'TRAIT_SPAIN': 'UNIT_TERCIO_2',
        },
        'UNIT_MERCHANT': {
            'TRAIT_MING': 'UNIT_MANDARIN',
            'TRAIT_SONGHAI': 'UNIT_TAJIRO',
        },
        'UNIT_MISSIONARY': {
            'TRAIT_HAWAII': 'UNIT_KAHUNA',
            'TRAIT_MAJAPAHIT': 'UNIT_PEDANDA',
        },
        'UNIT_PIKEMAN': {
            'TRAIT_HAWAII': 'UNIT_LEIOMANO_3',
            'TRAIT_MING': 'UNIT_XUNLEICHONG_3',
            'TRAIT_SONGHAI': 'UNIT_GOLD_BANGLES_3',
            'TRAIT_SPAIN': 'UNIT_TERCIO_3',
        },
        'UNIT_SCOUT': {
            'TRAIT_INCA': 'UNIT_CHASQUI',
        },
        'UNIT_SETTLER': {
            'TRAIT_NORMAN': 'UNIT_SOKEMAN',
        },
        'UNIT_SWORDSMAN': {
            'TRAIT_HAWAII': 'UNIT_LEIOMANO',
            'TRAIT_MING': 'UNIT_XUNLEICHONG',
            'TRAIT_SONGHAI': 'UNIT_GOLD_BANGLES',
            'TRAIT_SPAIN': 'UNIT_TERCIO',
        },
    },
    'Modern': {
        'UNIT_ARMY_COMMANDER': {
            'TRAIT_BUGANDA': 'UNIT_MWAMI',
        },
        'UNIT_ASSAULT_GUN': {
            'TRAIT_RUSSIA': 'UNIT_KATYUSHA_2',
        },
        'UNIT_AT_GUN': {
            'TRAIT_SIAM': 'UNIT_CHANG_BEUN_3',
        },
        'UNIT_BATTLESHIP': {
            'TRAIT_MEIJI': 'UNIT_MIKASA_2',
        },
        'UNIT_BIPLANE': {
            'TRAIT_MEIJI': 'UNIT_ZERO',
        },
        'UNIT_DIVEBOMBER': {
            'TRAIT_PRUSSIA': 'UNIT_STUKA_2',
        },
        'UNIT_DREADNOUGHT': {
            'TRAIT_MEIJI': 'UNIT_MIKASA',
        },
        'UNIT_FIELD_CANNON': {
            'TRAIT_SIAM': 'UNIT_CHANG_BEUN',
        },
        'UNIT_FIELD_GUN': {
            'TRAIT_SIAM': 'UNIT_CHANG_BEUN_2',
        },
        'UNIT_FIGHTER': {
            'TRAIT_MEIJI': 'UNIT_ZERO_2',
        },
        'UNIT_HEAVY_ARTILLERY': {
            'TRAIT_RUSSIA': 'UNIT_KATYUSHA',
        },
        'UNIT_INFANTRY_COMPANY': {
            'TRAIT_AMERICA': 'UNIT_MARINE_2',
            'TRAIT_BUGANDA': 'UNIT_ABAMBOWA_3',
            'TRAIT_FRENCH_EMPIRE': 'UNIT_GARDE_IMPERIALE_3',
            'TRAIT_MEXICO': 'UNIT_SOLDADERAS_3',
            'TRAIT_MUGHAL': 'UNIT_SEPOY_3',
            'TRAIT_QING': 'UNIT_GUSA_3',
        },
        'UNIT_LINE_INFANTRY': {
            'TRAIT_BUGANDA': 'UNIT_ABAMBOWA',
            'TRAIT_FRENCH_EMPIRE': 'UNIT_GARDE_IMPERIALE',
            'TRAIT_MEXICO': 'UNIT_SOLDADERAS',
            'TRAIT_MUGHAL': 'UNIT_SEPOY',
            'TRAIT_QING': 'UNIT_GUSA',
        },
        'UNIT_MERCHANT': {
            'TRAIT_QING': 'UNIT_HANGSHANG',
        },
        'UNIT_RIFLEMAN': {
            'TRAIT_AMERICA': 'UNIT_MARINE',
            'TRAIT_BUGANDA': 'UNIT_ABAMBOWA_2',
            'TRAIT_FRENCH_EMPIRE': 'UNIT_GARDE_IMPERIALE_2',
            'TRAIT_MEXICO': 'UNIT_SOLDADERAS_2',
            'TRAIT_MUGHAL': 'UNIT_SEPOY_2',
            'TRAIT_QING': 'UNIT_GUSA_2',
        },
        'UNIT_SETTLER': {
            'TRAIT_MUGHAL': 'UNIT_ZAMINDAR',
        },
        'UNIT_TRENCH_FIGHTER': {
            'TRAIT_PRUSSIA': 'UNIT_STUKA',
        },
    },
}
