"""Extract structured data from the local Civ 7 install XML.

Outputs Python data modules into `apworld/data/extracted/` that the
apworld then imports. Re-run after a Civ 7 patch to refresh.

Currently extracts:
- Tech node unlocks per Age
- Civic node unlocks per Age (common trees)
- Civ-unique civic trees (size per civ per Age)
- Wonder list per Age
- Pantheon beliefs (Antiquity)
- Discovery rewards

Religion beliefs (founder/follower/reliquary) are scoped for a later
extraction pass once we land capability 7.
"""

from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


CIV7_INSTALL = Path(
    "C:/Program Files (x86)/Steam/steamapps/common/Sid Meier's Civilization VII"
)
MODULES_ROOT = CIV7_INSTALL / "Base" / "modules"

REPO_ROOT = Path(__file__).resolve().parents[1]
EXTRACTED_DIR = REPO_ROOT / "apworld" / "data" / "extracted"


AGE_DIRS: dict[str, str] = {
    "Antiquity": "age-antiquity",
    "Exploration": "age-exploration",
    "Modern": "age-modern",
}


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------


def _find_rows(tree: ET.ElementTree, table_tag: str) -> list[ET.Element]:
    """Return all <Row> elements under the named table inside <Database>."""
    out: list[ET.Element] = []
    for table in tree.iter(table_tag):
        for row in table.findall("Row"):
            out.append(row)
    return out


def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _write_module(name: str, body: str, header: str = "") -> None:
    target = EXTRACTED_DIR / f"{name}.py"
    out = (
        '"""Generated by tests/extract_civ7_data.py from the Civ 7 install XML.\n'
        "Do not edit by hand; re-run the extractor.\n"
        f'{header}"""\n\n'
        + body
    )
    target.write_text(out, encoding="utf-8")
    print(f"[extract] wrote {target}")


# ---------------------------------------------------------------------
# Tech and civic unlocks
# ---------------------------------------------------------------------


@dataclass(frozen=True)
class UnlockEntry:
    target_kind: str
    target_type: str
    unlock_depth: int
    required_trait: str | None = None
    hidden: bool = False


def _parse_unlocks(xml_path: Path) -> dict[str, list[UnlockEntry]]:
    """Return {progression_tree_node_type: [UnlockEntry, ...]}."""
    tree = ET.parse(xml_path)
    out: dict[str, list[UnlockEntry]] = {}
    for row in _find_rows(tree, "ProgressionTreeNodeUnlocks"):
        node_id = row.get("ProgressionTreeNodeType")
        if not node_id:
            continue
        entry = UnlockEntry(
            target_kind=row.get("TargetKind", ""),
            target_type=row.get("TargetType", ""),
            unlock_depth=int(row.get("UnlockDepth", "1")),
            required_trait=row.get("RequiredTraitType") or None,
            hidden=row.get("Hidden", "false").lower() == "true",
        )
        out.setdefault(node_id, []).append(entry)
    return out


def _emit_unlocks(name: str, per_age: dict[str, dict[str, list[UnlockEntry]]]) -> None:
    """Emit a Python module declaring the per-Age unlock dictionaries."""
    lines = ["from dataclasses import dataclass\n",
             "\n",
             "@dataclass(frozen=True)\n",
             "class Unlock:\n",
             "    target_kind: str\n",
             "    target_type: str\n",
             "    unlock_depth: int\n",
             "    required_trait: str | None = None\n",
             "    hidden: bool = False\n",
             "\n",
             "\n"]
    for age, table in per_age.items():
        var = f"{age.upper()}_NODE_UNLOCKS"
        lines.append(f"{var}: dict[str, tuple[Unlock, ...]] = {{\n")
        for node_id, entries in sorted(table.items()):
            lines.append(f"    {node_id!r}: (\n")
            for e in entries:
                lines.append(
                    f"        Unlock({e.target_kind!r}, {e.target_type!r}, "
                    f"{e.unlock_depth}, "
                    f"{e.required_trait!r}, "
                    f"{e.hidden!r}),\n"
                )
            lines.append("    ),\n")
        lines.append("}\n\n")
    _write_module(name, "".join(lines))


def extract_tech_unlocks() -> None:
    per_age: dict[str, dict[str, list[UnlockEntry]]] = {}
    for age, age_dir in AGE_DIRS.items():
        path = MODULES_ROOT / age_dir / "data" / "progression-trees-tech.xml"
        per_age[age] = _parse_unlocks(path)
    _emit_unlocks("tech_unlocks", per_age)


def _parse_node_names(xml_path: Path) -> dict[str, str]:
    """Return {progression_tree_node_type: LOC_key} for each node in
    the file's <ProgressionTreeNodes> table.
    """
    if not xml_path.exists():
        return {}
    tree = ET.parse(xml_path)
    out: dict[str, str] = {}
    for row in _find_rows(tree, "ProgressionTreeNodes"):
        nid = row.get("ProgressionTreeNodeType")
        name = row.get("Name")
        if nid and name:
            out[nid] = name
    return out


def extract_node_names() -> None:
    """Emit the node_id -> LOC key mapping for every tech/civic node.

    The localization key is needed by the AP client to emit a per-seed
    <UpdateText> override XML that replaces vanilla node names with the
    AP item placed at each location.
    """
    mapping: dict[str, str] = {}
    for age, age_dir in AGE_DIRS.items():
        for fname in (
            "progression-trees-tech.xml",
            "progression-trees-culture-common.xml",
            "progression-trees-culture-unique.xml",
        ):
            path = MODULES_ROOT / age_dir / "data" / fname
            mapping.update(_parse_node_names(path))
    lines = ["NODE_NAME_LOC_KEYS: dict[str, str] = {\n"]
    for node_id, loc_key in sorted(mapping.items()):
        lines.append(f"    {node_id!r}: {loc_key!r},\n")
    lines.append("}\n")
    _write_module("node_names", "".join(lines))


def extract_civic_unlocks() -> None:
    """Civic-node unlocks span both the common civic tree
    (`progression-trees-culture-common.xml`) and the civilization-
    specific civic trees (`progression-trees-culture-unique.xml`).
    Merge unlocks from both files so e.g. NODE_CIVIC_AQ_ROME_CIVIS_ROMANUS
    correctly shows that it unlocks BUILDING_BASILICA.
    """
    per_age: dict[str, dict[str, list[UnlockEntry]]] = {}
    for age, age_dir in AGE_DIRS.items():
        merged: dict[str, list[UnlockEntry]] = {}
        for fname in (
            "progression-trees-culture-common.xml",
            "progression-trees-culture-unique.xml",
        ):
            path = MODULES_ROOT / age_dir / "data" / fname
            if not path.exists():
                continue
            for node_id, entries in _parse_unlocks(path).items():
                merged.setdefault(node_id, []).extend(entries)
        per_age[age] = merged
    _emit_unlocks("civic_unlocks", per_age)


# ---------------------------------------------------------------------
# Civ-unique civic trees
# ---------------------------------------------------------------------


def _parse_civ_unique_trees(xml_path: Path) -> dict[str, list[str]]:
    """Return {progression_tree_type: [node_type, ...]}, sorted by tree."""
    tree = ET.parse(xml_path)
    nodes_by_tree: dict[str, list[str]] = {}
    for row in _find_rows(tree, "ProgressionTreeNodes"):
        tree_type = row.get("ProgressionTree")
        node_type = row.get("ProgressionTreeNodeType")
        if not tree_type or not node_type:
            continue
        nodes_by_tree.setdefault(tree_type, []).append(node_type)
    return nodes_by_tree


def extract_civ_unique_trees() -> None:
    """Per Age: dict[civ-tree-id, list of node ids]. Includes max-size per Age."""
    per_age: dict[str, dict[str, list[str]]] = {}
    for age, age_dir in AGE_DIRS.items():
        path = MODULES_ROOT / age_dir / "data" / "progression-trees-culture-unique.xml"
        per_age[age] = _parse_civ_unique_trees(path)

    lines: list[str] = []
    for age, table in per_age.items():
        var = f"{age.upper()}_UNIQUE_CIVIC_TREES"
        lines.append(f"{var}: dict[str, tuple[str, ...]] = {{\n")
        for tree_id, nodes in sorted(table.items()):
            lines.append(f"    {tree_id!r}: (\n")
            for n in nodes:
                lines.append(f"        {n!r},\n")
            lines.append("    ),\n")
        lines.append("}\n\n")
        if table:
            sizes = sorted({len(v) for v in table.values()})
            max_size = max(len(v) for v in table.values())
            lines.append(f"{age.upper()}_UNIQUE_TREE_NODE_COUNTS: tuple[int, ...] = {tuple(sizes)!r}\n")
            lines.append(f"{age.upper()}_UNIQUE_MAX_NODES: int = {max_size}\n\n")
        else:
            lines.append(f"{age.upper()}_UNIQUE_TREE_NODE_COUNTS: tuple[int, ...] = ()\n")
            lines.append(f"{age.upper()}_UNIQUE_MAX_NODES: int = 0\n\n")
    _write_module("civ_unique_trees", "".join(lines))


# ---------------------------------------------------------------------
# Wonders
# ---------------------------------------------------------------------


def _parse_wonders(xml_path: Path) -> list[str]:
    """Return list of wonder constructible-type strings."""
    if not xml_path.exists():
        return []
    tree = ET.parse(xml_path)
    out: list[str] = []
    for row in _find_rows(tree, "Constructibles"):
        ctype = row.get("ConstructibleType", "")
        ctclass = row.get("ConstructibleClass", "")
        if ctclass == "WONDER" or ctype.startswith("WONDER_"):
            out.append(ctype)
    return out


def extract_wonders() -> None:
    per_age: dict[str, list[str]] = {}
    for age, age_dir in AGE_DIRS.items():
        path = MODULES_ROOT / age_dir / "data" / "constructibles.xml"
        per_age[age] = _parse_wonders(path)
    lines: list[str] = []
    for age, wonders in per_age.items():
        var = f"{age.upper()}_WONDERS"
        lines.append(f"{var}: tuple[str, ...] = (\n")
        for w in sorted(wonders):
            lines.append(f"    {w!r},\n")
        lines.append(")\n\n")
    _write_module("wonders", "".join(lines))


# ---------------------------------------------------------------------
# Pantheon beliefs (Antiquity)
# ---------------------------------------------------------------------


def extract_pantheon_beliefs() -> None:
    """Pantheon beliefs are declared in age-antiquity religion data."""
    candidates = [
        MODULES_ROOT / "age-antiquity" / "data" / "religion.xml",
    ]
    beliefs: list[str] = []
    for path in candidates:
        if not path.exists():
            continue
        tree = ET.parse(path)
        # Civ 7 'Beliefs' table; pantheon-class entries identifiable by BeliefClassType.
        for row in _find_rows(tree, "Beliefs"):
            belief_type = row.get("BeliefType", "")
            belief_class = row.get("BeliefClassType", "")
            if "PANTHEON" in belief_class.upper() or belief_class == "BELIEF_CLASS_PANTHEON":
                beliefs.append(belief_type)
    lines = [f"PANTHEON_BELIEFS: tuple[str, ...] = (\n"]
    for b in sorted(beliefs):
        lines.append(f"    {b!r},\n")
    lines.append(")\n")
    _write_module("pantheon_beliefs", "".join(lines))


# ---------------------------------------------------------------------
# Discovery rewards (Civ 7 Goody Huts)
# ---------------------------------------------------------------------


def _parse_discoveries(xml_path: Path) -> list[str]:
    if not xml_path.exists():
        return []
    tree = ET.parse(xml_path)
    out: list[str] = []
    for row in _find_rows(tree, "GoodyHuts"):
        t = row.get("GoodyHutType", "")
        if t:
            out.append(t)
    # Some Civ 7 builds use `<Discoveries>` table instead; check both.
    for row in _find_rows(tree, "Discoveries"):
        t = row.get("DiscoveryType", "") or row.get("Type", "")
        if t:
            out.append(t)
    return out


def extract_discoveries() -> None:
    per_age: dict[str, list[str]] = {}
    for age, age_dir in AGE_DIRS.items():
        path = MODULES_ROOT / age_dir / "data" / "goody-huts.xml"
        per_age[age] = _parse_discoveries(path)
    lines: list[str] = []
    for age, types in per_age.items():
        var = f"{age.upper()}_DISCOVERY_TYPES"
        lines.append(f"{var}: tuple[str, ...] = (\n")
        for t in sorted(set(types)):
            lines.append(f"    {t!r},\n")
        lines.append(")\n\n")
    _write_module("discoveries", "".join(lines))


# ---------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------


def main() -> int:
    if not CIV7_INSTALL.exists():
        print(f"Civ 7 install not found at {CIV7_INSTALL}")
        return 1
    _ensure_dir(EXTRACTED_DIR)
    init = EXTRACTED_DIR / "__init__.py"
    if not init.exists():
        init.write_text("# Generated extraction modules.\n", encoding="utf-8")

    extract_tech_unlocks()
    extract_civic_unlocks()
    extract_civ_unique_trees()
    extract_node_names()
    extract_wonders()
    extract_pantheon_beliefs()
    extract_discoveries()

    print("[extract] done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
